name: workflow.yml
on: push

jobs:
  test_echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test (inline script)
        run: echo "Test"
      - name: Echo hello world (source script)
        working-directory: scripts
        run: source test.sh
